spring.application.name=Notificaciones
server.port=${PORT:8081}
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/MSNotificaciones?createDatabaseIfNotExist=true
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:Villita71}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

eureka.client.enabled=false

bot.security.username=${BOT_SECURITY_USERNAME:bot_consultas@ayuntamiento.com}
bot.security.password=${BOT_SECURITY_PASSWORD:mO5gg7XWbO4rhU2Zu7XAjWEEAV0VT5!}
jwt.rsa.public-key=${JWT_RSA_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtb374qvIdtKg8/mN4NAHzN5gVo2fq5t48HIbhPPA1qqgrMzmx4yJIPQZgKNGA9+J59zyqpjBnHOdY+k7qsrqNwIbICMs7FmOSkfmVorbNIWP+CeOQG1s2CY9YNahH5b/HOIfK9piPSx+Znpf/9KhPoN0/k9mvd4mL/zntIOPu+RaR5JST/Sl7w4tUgAWB7eklLlXXeSXoXYWbOfSNK2b50KXkkCozma4EqzMwhe8K7AAfp3CBFQNhV6fjtPjF/Z7bgM/V8DqA8QnJ4nZRWBwEbG6Vc1KvYYRAl9X6IIqBHgMZD8hCzSpMXSemVWPnmPf499896RW/DQ3lGnBcV4X8QIDAQAB}

spring.main.allow-bean-definition-overriding=true